%LdeP Parameter values
J=5*(10^4); %Resting macrophage influx: cells/ml day;
k = [0.4]; %Activated Macrophage deactivation rate: 1/day
b = 0.09; %Recruitment rate of macrophages by activated macrophages: 1/day
c = 0.1; %Macrophage egress rate: 1/day
e1 = 1*10^(-8); %Effect of crowding on macrophages: 1/cells day
e2 = 1*10^(-8); %Effect of crowding on active macrophages: 1/cells day
fMb = 0.0623*(2*10^(-5)); %Rates macrophages engulf necrotic and apoptotic Beta cells; Balb/c mice: ml/cells days
fMn = 0.0623*(1*10^(-5)); %Rates macrophages engulf necrotic and apoptotic Beta cells; NOD mice: ml/cells days
Ab = 0.0334; %Rate Beta cells are produced from glucose
Ghb = 90; %Glucose level of half-max Beta cell production: mg/dl
dB = 0.0167; %Beta cell death rate: 1/day
Qpanc = 0.194; %Volume of mouse pancreas: ml
Bconv = 2.59*10^5; %Beta cells per miligram: cells/mg
eta = 0.02; %Rate at which T cells eliminate Beta cells: 1/days
sE = 1; %Relative impact of effector T cells on Beta cell death: ml/cells
sR = 36; %Relative impact of regulatory T cells on Beta cell death: ml/cells
d = 0.50; %Beta cell rate of necrosis: 1/day
fD = 1.71*10^(-7); %Rate DCs engulf Beta cells: ml/cells days
ftD = 1.19*10^(-6); %Rate native or tolerogenic DCs engulf Beta cells: ml/cells days
fMab = 0.0623*(5*10^(-5)); %Rate activated macrophages engulf necrotic and apoptotic Beta cells; Balb/c mice: ml/cells days
fMan = 0.0623*(1*10^(-5)); %Rate activated macrophages engulf necrotic and apoptotic Beta cells; NOD mice: ml/cells days
Dss = 1*10^5; %Steady-state DC population: cells/ml
R0 = 864; %Basal rate of glucose production: mg/dl
G0 = 1.44; %Rate of glucose decay: 1/day
SI = 0.72; %Rate of glucose elimination via insulin: ml/microU/day
GI = sqrt(20000); %Glucose level of half-max insulin production: mg/dl
sigmaI = 43.2; %Maximum rate of insulin production by Beta cells: microU/ml/d/mg
dI = 432; %Rate of insulin decay: 1/day
bDE = 0.487*10^(-5); %Rate of elimination of DCs by effector T cells: ml/cells/day
bIR = 0.487*10^(-5); %Rate of elimination of tDCs by regulatory T cells: ml/cells/day
mD = 0.51; %Rate of removal from pancreas for DC and tDC: 1/day
aE = 0.1199; %Rate of initial expansion of naive T cells into effector T cells: 1/day
aR = 0.1199; %Rate of initial expression of naive T cells into regulatory T cells: 1/day
Tnaive = 370; %Density of naive T cells contributing to initial production of Teff and Treg in the spleen: cells/ml
bP = 12; %Maximal expansion rate of Teff and Treg cells due to DCs: 1/day
ram = 0.01; %Reversion rate of Teff and Treg cells to memory T cells: 1/day
bE = 1*10^(-3); %Activation rate of effector T cells from memory T cells: (ml d)/cells
mE = 2*10^(-6); %Rate of effector T cell removal due to regulatory T cell: 1/day
thetaD = 2.12*10^5; %DC value for half-maximal effector T cell expansion: 1/day
bR = 1*10^(-3); %Activation rate for regulatory T cells from memory T cells: (ml d)/cells
mR = 2*10^(-6); %Rate of regulatory T cell removal due to effector T cell: 1/day
aEm = 0.01; %Death rate of memory T cells: 1/day
Ae = 0.11; % Eta function term
Be = 21; % Eta function term
Waveon = 0; %This functions as an on/off switch for the wave function (W). TO turn on, change to 1. To turn off, change to 0.
